name: package_documents
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo
publish_to: none

environment:
  sdk: ^3.10.8

# Add regular dependencies here.
dependencies:
  path: ^1.9.0
  yaml: ^3.1.3
  claw_shelf:
    path: ../..
  isar: ^3.1.0+1
  isar_flutter_libs:
    git:
      url: https://github.com/MrLittleWhite/isar_flutter_libs.git
  path_provider: ^2.1.5

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.6
  isar_generator: ^3.1.0+1
  build_runner: ^2.4.13
