name: Signal Github Pages
on:
  push:
    branches: [ main ]

jobs:
  ping_app:
    runs-on: ubuntu-latest
    steps:
      - name: Emit Repository Dispatch
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ secrets.PAT_TOKEN }}
          repository: ClawShelf/clawshelf.github.io # The target repo
          event-type: content_updated     # A custom ID for the receiver